#pragma once

#define TAPPING_TERM 180
#define PERMISSIVE_HOLD

#ifdef RGB_MATRIX_ENABLE
#    define RGB_DISABLE_WHEN_USB_SUSPENDED true
#    define RGB_MATRIX_KEYPRESSES
#    undef RGB_MATRIX_MAXIMUM_BRIGHTNESS
#    define RGB_MATRIX_MAXIMUM_BRIGHTNESS 120
#endif
